spring:
  profiles:
    active: dev
  application:
    name: telemetry
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/master-changelog.yaml
    liquibase-schema: service

preliquibase:
  sql-script-references: classpath:db/changelog/share/create-service-schema.sql
cors:
  allowed-origins: http://localhost:3000