services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: telemetry_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
    volumes:
      - telemetry_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  telemetry_data: